function [NodeXYCoordinate, ElementConnectivity, NodeData_DRM_inner, NodeData_DRM_outer, ElementData_DRM] = fun_MeshInfor_LSDYNA
%--------------------------------------------------------------------------
% Originally written by Wenyang Zhang
% Email: zwyll@ucla.edu
% Data : 09/12/2018
%
% Modified by Yiwen
% Data : 11/25/2025
%
% This code exports node and element info in your big model.
%----------------------------------------
% YOU MUST MODIFY THIS FUNCTION.
%
% Modification instruction:
%   - understand the output variables, read the variables from keyword files
%----------------------------------------
%
%
% INPUT:
%       (NONE, modify the main body of this function)
%
% OUTPUT:
%       NodeXYCoordinate   : nnodes by 6 matrix, nodal coordinates info
%                            (automatically generated by LS-DYNA)
%                                   column 1: node number
%                                   column 2~4: x, y, z coordinates
%                                   column 5~6: useless, neglect
%
%       ElementConnectivity: nele by 10 matrix, element connectivity info
%                             (automatically generared by LS-DYNA)
%                                   column 1: element number
%                                   column 2: part id of element
%                                   column 3~10: 8 node number of cubic element
%
%       NodeData_DRM_inner : vector, node number of inner DRM nodes
%
%       NodeData_DRM_outer : vector, node number of outer DRM nodes
%
%       ElementData_DRM    : neleDRM by 4 matrix
%                                   column 1: DRM element number 
%                                   column 2: mass density of the element
%                                   column 3: Young's modulus of the
%                                               element
%                                   column 4: Poisson' ratio of the element
%
%
%----------------------------------------
% YOU MUST MODIFY THIS FUNCTION.
%--------------------------------------------------------------------------


% read ls-dyna keyword file
fid = fopen('r11fromre8ver3_readytorun.k');
cac = textscan( fid, '%s', 'Delimiter','\n', 'CollectOutput',true, 'Whitespace',''); 
cac = cac{1};

% read node coordinates info from the input file    
NodeXYCoordinate = str2num(char(cac(3135:107033)));

% read element connectivity info from the input file    
ElementConnectivity = str2num(char(cac(127197:223792)));

% read inside DRM interface nodes' number info from the input file
% it is recommended to create a node set in the model in advance and read
%   the nodeset
NodeData_DRM_inner = str2num(char(cac(224979:225777)));
NodeData_DRM_inner = reshape(NodeData_DRM_inner',[size(NodeData_DRM_inner,1)*size(NodeData_DRM_inner,2),1]);
NodeData_DRM_inner = NodeData_DRM_inner(NodeData_DRM_inner ~= 0);

% read outside DRM interface nodes' number info from the input file    
% it is recommended to create a node set in the model in advance and read
%   the nodeset
NodeData_DRM_outer = str2num(char(cac(225783:226652)));
NodeData_DRM_outer = reshape(NodeData_DRM_outer',[size(NodeData_DRM_outer,1)*size(NodeData_DRM_outer,2),1]);
NodeData_DRM_outer = NodeData_DRM_outer(NodeData_DRM_outer ~= 0);

% read DRM interface elements' number info from the input file    
% it is recommended to create an element set in the model in advance and
% read the element set
ElementData_DRM = str2num(char(cac(228817:229641)));
ElementData_DRM = reshape(ElementData_DRM',[size(ElementData_DRM,1)*size(ElementData_DRM,2),1]);
ElementData_DRM = ElementData_DRM(ElementData_DRM ~= 0);

% read part info
PartInfo = [];
% PartInfo
%   column 1: part id
%   column 2: section id
%   column 3: material id
%   column 4~8: useless
i = 127076;
while i<127194
    if contains(char(cac(i)), '*PART')
        i=i+4;
        PartInfo = [PartInfo; str2num(char(cac(i)))];
    end
    i=i+1;
end

% read material info
MatInfo = [];
%   column 1: mat id
%   column 2: mass density
%   column 3: Young's modulus
%   column 4: Poisson's ratio
%   column 5~7: useless
i = 3093;
while i<3133
    if contains(char(cac(i)), '*MAT_ELASTIC_TITLE')
        i=i+3;
        temp = [];
        st = char(cac(i));
        for j=1:4
            temp = [temp str2num(st(10*(j-1)+1: 10*j))];
        end
        MatInfo = [MatInfo; temp];
    end
    i=i+1;
end

% connect MatInfo and ElementData_DRM
ElementData_DRM = [ElementData_DRM zeros(length(ElementData_DRM),3)];
for i=1:size(ElementData_DRM,1)
    elementindex = find(ElementConnectivity(:,1) == ElementData_DRM(i,1));
    partid = ElementConnectivity(elementindex,2);
    partindex = find(PartInfo(:,1) == partid);
    matid = PartInfo(partindex ,3);
    matindex = find(MatInfo(:,1) == matid);
    ElementData_DRM (i, 2:4) = MatInfo (matindex, 2:4);
end

end