function [Ue, Uedot, Ueddot, t] = fun_NodalResponseAssembly(nnodesDRM, DRM_Node_Coords)
%--------------------------------------------------------------------------
% Originally written by Wenyang Zhang
% Email: zwyll@ucla.edu
% Data : 09/12/2018
%
% Modified by Yiwen
% Data : 11/25/2025
%
% This code assembles 1D nodal input from 1D SRA.
%----------------------------------------
% YOU MUST MODIFY THIS FUNCTION.
%
% Modification instruction:
%   - run your 1D SRA and DRM_response_Homo.mat, make sure the .mat file
%        is compatible with the format list below (2 vectors and 3
%        matrices)
%----------------------------------------
%
% INPUT:
%       nnodesDRM          : number of DRM nodes (including inner and outer
%                               DRM nodes)
%
%       DRM_Node_Coords   : nnodesDRM by 6 matrix, nodal coordinates info
%                           of DRM nodes
%                            (automatically generated by LS-DYNA)
%                                   column 1: node number
%                                   column 2~4: x, y, z coordinates
%                                   column 5~6: useless, neglect
%
% OUTPUT:
%       Ue, Uedot, Ueddot  : each nnodesDRM*3 by n matrix. displacement, 
%           velocity and acceleration info,
%
%       t                  : time, a vector.
%
%
%----------------------------------------
% YOU MUST MODIFY THIS FUNCTION.
%--------------------------------------------------------------------------

% total number of DOFs for the DRM nodes, i.e., DOFs = 3 for each node 
nGlDRMDof = 3*nnodesDRM;

% %-------------------------------------------------------------------------- 
% load the free-field motion from 1D site response analysis
load DRM_response_Homo.mat 
% Run "Site_response_analysis_vertical_SV_wave.m" fist to get
%   "DRM_response_Homo.mat". You may define your own version of 1D SRA.
%
% DRM_response_Homo.mat contains 2 vectors and 3 matrices:
%   1) t               :vector, time
%   2) depth           :vector, depth of layer, all non-negative number,
%                           starting from zero
%
%   3) u_history       :matrix, displacement time series
%   4) udot_history    :matrix, velocity times series
%   5) uddot_history   :acceleration, acceleration times series
%
% Each matrix is a nlayer by n matrix
%   - nlayer: number of soil layer in 1D site response analysis
%   - n: length of time vector
% %-------------------------------------------------------------------------- 

% length of time vector
n = length(t);

% initialization of acceleration, velocity and displacement response    
Ueddot = zeros(nGlDRMDof,n);
Uedot = zeros(nGlDRMDof,n);
Ue = zeros(nGlDRMDof,n);

% computing the response for all DRM nodes
linelength = 0;
for i = 1:n
    fprintf(repmat('\b',1,linelength));
    linelength = fprintf('nodal response assembly: time step %d/%d', i, n);
    
    for j = 1:nnodesDRM 
        coords = DRM_Node_Coords(j,2:4);        
        node_loc = find((-depth)==coords(3));
        
        U(1) = u_history(node_loc(1),i);
        U(2) = udot_history(node_loc(1),i);
        U(3) = uddot_history(node_loc(1),i);
        
        V = zeros(1,3);
        W = zeros(1,3);
        
        Ueddot(j,i) = U(3);
        Uedot(j,i) = U(2);
        Ue(j,i) = U(1);
        Ueddot(j+nnodesDRM,i) = V(3);
        Uedot(j+nnodesDRM,i) = V(2);
        Ue(j+nnodesDRM,i) = V(1);
        Ueddot(j+nnodesDRM*2,i) = W(3);
        Uedot(j+nnodesDRM*2,i) = W(2);
        Ue(j+nnodesDRM*2,i) = W(1);
    end       
end

fprintf('\n');

end